<template>
  <view class="page-shell"><view class="status-space" /><view class="topbar"><text class="back" @tap="back">‹</text><text class="bar-title">空间文章</text><text class="edit" @tap="edit">编辑</text></view><scroll-view class="page-scroll" scroll-y><view v-if="loading" class="state">正在打开文章…</view><view v-else-if="!note" class="state">文章暂时不可见。</view><view v-else class="article"><image v-if="normalizeAssetUrl(note.cover_url)" class="cover" :src="normalizeAssetUrl(note.cover_url)" mode="aspectFill" lazy-load /><text class="title">{{ note.title }}</text><view class="meta"><text>{{ authorName }}</text><text>{{ formatDate(note.updated_at || note.created_at) }}</text><text v-if="note.lock_by" class="lock">编辑中</text></view><view class="content"><text selectable class="body">{{ note.content || '作者暂未填写正文。' }}</text></view></view></scroll-view></view>
</template>

<script>
import { getSpaceNote, normalizeAssetUrl } from '../../services/api'
export default { data() { return { spaceId: '', noteId: '', note: null, loading: true } }, onLoad(query) { this.spaceId = query.spaceId || ''; this.noteId = query.noteId || ''; this.loadNote() }, computed: { authorName() { return this.note && this.note.author ? (this.note.author.display_name || this.note.author.username || '空间成员') : '空间成员' } }, methods: { normalizeAssetUrl, async loadNote() { if (!this.spaceId || !this.noteId) { this.loading = false; return } try { this.note = await getSpaceNote(this.spaceId, this.noteId) } catch (error) { this.note = null } finally { this.loading = false } }, back() { uni.navigateBack({ delta: 1 }) }, edit() { if (this.note) uni.navigateTo({ url: '/pages/note-editor/index?spaceId=' + this.spaceId + '&noteId=' + this.noteId }) }, formatDate(value) { if (!value) return '刚刚'; const date = new Date(value); return date.getFullYear() + '.' + String(date.getMonth() + 1).padStart(2, '0') + '.' + String(date.getDate()).padStart(2, '0') } } }
</script>

<style scoped>
.page-shell{height:100vh;overflow:hidden;background:#f1eee5}.status-space{height:var(--status-bar-height);background:#f8f6f0}.topbar{height:100rpx;padding:0 28rpx;display:flex;align-items:center;justify-content:space-between;background:#f8f6f0;border-bottom:1rpx solid rgba(23,33,29,.08)}.back{width:56rpx;color:#163a2b;font-size:58rpx;line-height:54rpx}.bar-title{color:#17211d;font-family:Georgia,'Songti SC',serif;font-size:27rpx;font-weight:700}.edit{width:56rpx;color:#1d6347;font-size:21rpx;text-align:right}.page-scroll{height:calc(100vh - var(--status-bar-height) - 100rpx)}.state{padding:160rpx 30rpx;color:rgba(23,33,29,.48);font-size:23rpx;text-align:center}.article{padding:28rpx 30rpx 80rpx}.cover{width:100%;height:360rpx;margin-bottom:34rpx;border-radius:32rpx;background:#e4ecdf}.title{display:block;color:#17211d;font-family:Georgia,'Songti SC',serif;font-size:45rpx;font-weight:700;line-height:62rpx}.meta{display:flex;flex-wrap:wrap;gap:12rpx 20rpx;margin-top:22rpx;color:rgba(23,33,29,.46);font-size:19rpx}.lock{color:#9b611f}.content{margin-top:34rpx;padding-top:30rpx;border-top:1rpx solid rgba(23,33,29,.1)}.body{display:block;color:#28332d;font-size:25rpx;line-height:45rpx;white-space:pre-wrap;word-break:break-word}
</style>
