"""change chat model to string

Revision ID: ee7e073187c6
Revises: 475aeda4644c
Create Date: 2026-06-04 18:52:58.540639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ee7e073187c6'
down_revision: Union[str, None] = '475aeda4644c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_sessions', 'model',
               existing_type=mysql.ENUM('QWEN', 'DEEPSEEK', collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_sessions', 'model',
               existing_type=sa.String(length=100),
               type_=mysql.ENUM('QWEN', 'DEEPSEEK', collation='utf8mb4_unicode_ci'),
               existing_nullable=False)
    # ### end Alembic commands ###
